force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Min_Pay__c.field-meta.xml
<CustomField>
    <fullName>Min_Pay__c</fullName>
    <label>Min Pay</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Open-Approval</fullName>
            </value>
            <value>
                <fullName>Closed-Filled</fullName>
            </value>
            <value>
                <fullName>Closed-Not Approval</fullName>
            </value>
            <value>
                <fullName>Closed-Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PositionTriggerHandler.cls
public class PositionTriggerHandler {

    public static void populateDateAndPay(List<Position__c> posList){
        for(Position__c objPos: posList){
            if(objPos.Status__c== 'New Position' && objPos.Open_Date__c== null && objPos.Max_Pay__c== null && objPos.Min_Pay__c== null){
                objPos.Open_Date__c= system.today();
                objPos.Min_Pay__c= 10000;
                objPos.Max_Pay__c= 15000;
            }
        }
    }
}